---

name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '11 23 * * 0'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file:    ./docker/Dockerfile
          push:    true
          tags:    devopsansiblede/acme_certs_extract:latest

      - name: Image digest
        run:  echo ${{ steps.docker_build.outputs.digest }}

      - name: Last Build
        run:  sed -i -E "s/^[0-9]{4}-[0-9]{2}-[0-9]{2}\s+[0-9]{2}:[0-9]{2}:[0-9]{2}$/$( date +"%Y-%m-%d %T" )/" README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message:    Last built
          commit_user_name:  GitHub Actions
          commit_user_email: dev@macwinnie.me

...
